{{- if gt (.Values.workersNumber | int) 0 }}
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ .Values.clusterName }}-worker-bootstrap
  namespace: {{ .Values.clusterNamespace }}
  labels:
    {{- include "openstack-enhanced-cp.labels" . | nindent 4 }}
spec:
  template:
    spec:
      preK0sCommands:
      - mkdir -p /etc/kubernetes
{{- end }} 